import create from 'zustand';
import { persist } from 'zustand/middleware';

const popularTickers = ['AAPL', 'TSLA', 'GOOGL', 'MSFT', 'NVDA', 'AMZN', 'META', 'SPY', 'QQQ', 'BTC-USD', 'ETH-USD'];

export const useStore = create(
  persist(
    (set, get) => ({
      ticker: 'AAPL',
      timeframe: '1D',
      candles: [],
      predictions: null,
      dataSource: 'Yahoo Finance',
      isLoadingData: false,
      dataError: null,
      isTraining: false,
      trainingProgress: 0,
      trainingLoss: null,
      modelData: null,
      modelCached: false,
      isRunningPrediction: false,
      patterns: [],
      activePatternId: null,
      showVolume: true,
      showConfidenceBands: true,
      showRSI: true,
      showMA: true,
      showBollingerBands: true,
      showMACD: true,
      activeSidebarTab: 'patterns',
      sidebarCollapsed: false,
      numFutureCandles: 10,
      numSimulations: 60,
      predictionMode: 'neural',
      apiKeys: {
        TWELVE_DATA_KEY: '',
        FMP_KEY: '',
        FINNHUB_KEY: '',
        ALPHA_VANTAGE_KEY: '',
      },
      globalTrainingSamples: 0,
      globalTrainingTickers: 0,
      popularTickers,
      setTicker: (ticker) => set({ ticker }),
      setTimeframe: (timeframe) => set({ timeframe }),
      setCandles: (candles) => set({ candles }),
      setPredictions: (predictions) => set({ predictions }),
      setDataSource: (source) => set({ dataSource: source }),
      setIsLoadingData: (value) => set({ isLoadingData: value }),
      setDataError: (error) => set({ dataError: error }),
      setIsTraining: (state) => set({ isTraining: state }),
      setTrainingProgress: (progress) => set({ trainingProgress: progress }),
      setTrainingLoss: (loss) => set({ trainingLoss: loss }),
      setModelData: (modelData) => set({ modelData, modelCached: !!modelData }),
      setPatterns: (patterns) => set({ patterns }),
      setActivePatternId: (id) => set({ activePatternId: id }),
      setShowVolume: (show) => set({ showVolume: show }),
      setShowConfidenceBands: (show) => set({ showConfidenceBands: show }),
      setShowRSI: (show) => set({ showRSI: show }),
      setShowMA: (show) => set({ showMA: show }),
      setShowBollingerBands: (show) => set({ showBollingerBands: show }),
      setShowMACD: (show) => set({ showMACD: show }),
      setActiveSidebarTab: (tab) => set({ activeSidebarTab: tab }),
      setSidebarCollapsed: (collapsed) => set({ sidebarCollapsed: collapsed }),
      setNumFutureCandles: (count) => set({ numFutureCandles: count }),
      setNumSimulations: (count) => set({ numSimulations: count }),
      setPredictionMode: (mode) => set({ predictionMode: mode }),
      setApiKeys: (apiKeys) => set({ apiKeys }),
      addGlobalTrainingSamples: (count) => set((state) => ({ globalTrainingSamples: state.globalTrainingSamples + count })),
      addGlobalTrainingTickers: () => set((state) => ({ globalTrainingTickers: state.globalTrainingTickers + 1 })),
      resetGlobalStats: () => set({ globalTrainingSamples: 0, globalTrainingTickers: 0 }),
    }),
    {
      name: 'ghostcandle_state',
      partialize: (state) => ({ apiKeys: state.apiKeys, sidebarCollapsed: state.sidebarCollapsed, activeSidebarTab: state.activeSidebarTab }),
    },
  ),
);
